# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='board_pk',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
    ]
