# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topics_board_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='board_pk',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
